# Generated by Django 4.2 on 2023-04-26 11:18

from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], default=payment.models.PaymentStatus['PENDING'], max_length=63)),
                ('type', models.CharField(choices=[('PAYMENT', 'PAYMENT'), ('FINE', 'FINE')], default=payment.models.PaymentType['PAYMENT'], max_length=63)),
                ('session_url', models.URLField(max_length=255)),
                ('session_id', models.CharField(max_length=63)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('borrowing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrowing.borrowing')),
            ],
        ),
    ]
